/**
 * CENTRAL DECIMAL BOUNDARY (Float→Decimal migration).
 *
 * The database now stores exact DECIMAL(15,2)/(15,4) columns (see
 * prisma/schema.prisma). Prisma returns those as Decimal objects, which
 * would break every `a + b` in the codebase AND cannot cross the tRPC
 * superjson boundary. This extension converts Decimal→number on every
 * operation result (model reads, aggregates, groupBy) via a deep walker,
 * so all application code keeps working with plain numbers.
 *
 * Writes need no conversion: Prisma natively accepts `number` inputs for
 * Decimal columns.
 *
 * The companion script scripts/patch-prisma-decimal-types.mjs rewrites the
 * GENERATED TypeScript declarations (Decimal → number) after every
 * `prisma generate`, so static types match this runtime behavior.
 *
 * JS numbers have a 53-bit mantissa (~15-16 significant digits); NPR
 * amounts up to 999,999,999,999.99 (14 digits) round-trip exactly.
 * The exactness that matters — DB-level SUM() aggregation — is what this
 * migration buys; app-level arithmetic keeps the existing round2()
 * defense (src/lib/decimal-precision.ts).
 *
 * GENERATED by scripts/decimal-migration.mjs — do not edit by hand.
 */
import { Prisma } from "@prisma/client";

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return (
    typeof v === "object" &&
    v !== null &&
    !Array.isArray(v) &&
    !(v instanceof Date) &&
    !Buffer.isBuffer(v) &&
    !(v instanceof Uint8Array) &&
    !(v instanceof Prisma.Decimal)
  );
}

/** Recursively convert Decimal instances to plain numbers. */
export function deepToNumbers<T>(value: T): T {
  if (value instanceof Prisma.Decimal) return value.toNumber() as unknown as T;
  if (Array.isArray(value)) return value.map((v) => deepToNumbers(v)) as unknown as T;
  if (isPlainObject(value)) {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value)) out[k] = deepToNumbers(v);
    return out as unknown as T;
  }
  return value;
}

export const decimalBoundary = Prisma.defineExtension({
  name: "decimalBoundary",
  query: {
    $allModels: {
      async $allOperations({ args, query }) {
        return deepToNumbers(await query(args));
      },
    },
  },
});
