/**
 * ESLint Ratchet Allowlists — GENERATED FILE
 *
 * The ratchet pattern: the banned-pattern rules are ERRORS for the whole
 * repo, except for files listed here that already violate them today.
 *
 *   - LEGACY_RAW_TABLE_FILES : files still rendering raw <table> instead of
 *     <ConstructionTable /> (Engine Protocol). Shrinks as domains migrate.
 *   - LEGACY_TO_LOCALE_FILES : files calling .toLocaleString() instead of
 *     formatNpr() from @/lib/construction-finance. Shrinks as domains migrate.
 *
 * RULES OF THE RATCHET:
 *   1. NEVER add a file to these lists in a PR that introduces new violations.
 *   2. Removing a line is always welcome (the file was migrated).
 *   3. CI treats list growth as review-blocking drift.
 *
 * Permanently sanctioned raw-table sites (the engines themselves):
 *   - src/components/ui/table.tsx        (shadcn primitive)
 *   - src/components/ui/construction-table.tsx (ConstructionTable engine)
 *
 * Generated: 2026-09-01T07:40:19.074Z
 * Counts at generation: rawTable=65 (excluding 2 engines), toLocaleString=90
 */

export const LEGACY_RAW_TABLE_FILES = [
  "src/app/(app)/admin/material-catalog/components/archived-catalog-table.tsx",
  "src/app/(app)/admin/material-catalog/components/excel-material-importer.tsx",
  "src/app/(app)/finance/components/org-inventory-tab.tsx",
  "src/app/(app)/finance/components/org-payables-tab.tsx",
  "src/app/(app)/presets/page.tsx",
  "src/app/(app)/projects/\\[id\\]/accounting/components/ledger-accounts-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/analysis-library-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/boq-table.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/boq-versions-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/fiscal-year-switch-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/inline-analysis-editor.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/rates-library.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/read-only-rate-analysis.tsx",
  "src/app/(app)/projects/\\[id\\]/document-center/page.tsx",
  "src/app/(app)/projects/\\[id\\]/equipment/components/spot-hire-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/equipment/utilization/page.tsx",
  "src/app/(app)/projects/\\[id\\]/forms/page.tsx",
  "src/app/(app)/projects/\\[id\\]/gantt/components/GanttAnalysisModals.tsx",
  "src/app/(app)/projects/\\[id\\]/gantt/components/ResourceLoading.tsx",
  "src/app/(app)/projects/\\[id\\]/gantt/components/ResourcePage.tsx",
  "src/app/(app)/projects/\\[id\\]/guarantees/page.tsx",
  "src/app/(app)/projects/\\[id\\]/hr/components/advances-ledger-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/hr/components/daily-attendance-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/hr/components/leaves-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/hr/components/muster-roll-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/hr/components/staff-directory-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/ipc/\\[ipcId\\]/components/ipc-payment-summary-sheet.tsx",
  "src/app/(app)/projects/\\[id\\]/ipc/\\[ipcId\\]/components/ipc-version-diff.tsx",
  "src/app/(app)/projects/\\[id\\]/ipc/\\[ipcId\\]/page.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/po-print-view.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/quotation-comparison-matrix.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/requisition-detail-view.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/dialogs/inward-delivery-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/payments/components/aging-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/payments/components/bulk-import-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/payments/components/retention-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/payments/page.tsx",
  "src/app/(app)/projects/\\[id\\]/planning/revision/\\[versionId\\]/page.tsx",
  "src/app/(app)/projects/\\[id\\]/subcontractors/billing/components/material-reconciliation-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/subcontractors/billing/components/reconciliation-matrix-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/subcontractors/billing/dialogs/verify-bill-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/subcontractors/billing/page.tsx",
  "src/app/(app)/projects/\\[id\\]/subcontractors/page.tsx",
  "src/app/(app)/projects/\\[id\\]/tax-summary/components/missing-scans-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/tax-summary/components/vat-return-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/variations/\\[voId\\]/page.tsx",
  "src/app/(app)/projects/\\[id\\]/vendors/components/vendor-detail-view.tsx",
  "src/app/(app)/projects/\\[id\\]/workflow/program/components/add-program-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/workflow/program/components/task-table.tsx",
  "src/app/(app)/projects/\\[id\\]/workflow/program/my-tasks/page.tsx",
  "src/app/(app)/projects/\\[id\\]/workflow/program/page.tsx",
  "src/app/(app)/projects/\\[id\\]/workflow/reports/\\[reportId\\]/print/page.tsx",
  "src/app/(app)/projects/\\[id\\]/workflow/rfi/components/csv-import-form.tsx",
  "src/app/(app)/projects/\\[id\\]/workflow/rfi/components/rfi-table.tsx",
  "src/components/catalog/catalog-view.tsx",
  "src/components/dashboard/cross-project-financials-card.tsx",
  "src/components/inventory/reconciliation-report.tsx",
  "src/components/report-designer/report-renderer.tsx",
  "src/components/reports/equipment-view.tsx",
  "src/components/reports/manpower-view.tsx",
  "src/components/reports/meetings-view.tsx",
  "src/components/reports/visitors-view.tsx",
  "src/components/ui/data-table.tsx",
  "src/components/workflow/rfi-linked-boq-section.tsx",
  "src/components/workflow/view-rfi-dialog.tsx",
];

export const LEGACY_TO_LOCALE_FILES = [
  "src/app/(app)/admin/material-catalog/components/sync-catalog-dialog.tsx",
  "src/app/(app)/finance/components/org-inventory-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/add-boq-item-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/boq-row.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/boq-section-group.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/boq-table.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/boq-versions-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/catalog-rates-table.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/fiscal-year-switch-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/inline-add-row.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/inline-analysis-editor.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/rate-analysis-inspector.tsx",
  "src/app/(app)/projects/\\[id\\]/boq/components/read-only-rate-analysis.tsx",
  "src/app/(app)/projects/\\[id\\]/correspondence/components/letter-detail-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/equipment/components/equipment-maintenance-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/equipment/dialogs/log-spot-hire-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/forms/page.tsx",
  "src/app/(app)/projects/\\[id\\]/gantt/components/BoqAttachmentPanel.tsx",
  "src/app/(app)/projects/\\[id\\]/gantt/components/GanttAnalysisModals.tsx",
  "src/app/(app)/projects/\\[id\\]/gantt/components/ResourcePage.tsx",
  "src/app/(app)/projects/\\[id\\]/gantt/components/TaskInspector.tsx",
  "src/app/(app)/projects/\\[id\\]/gantt/components/TaskRow.tsx",
  "src/app/(app)/projects/\\[id\\]/guarantees/page.tsx",
  "src/app/(app)/projects/\\[id\\]/hr/components/daily-attendance-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/hr/components/muster-roll-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/hr/components/staff-directory-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/ipc/\\[ipcId\\]/components/helpers.ts",
  "src/app/(app)/projects/\\[id\\]/ipc/\\[ipcId\\]/components/ipc-version-diff.tsx",
  "src/app/(app)/projects/\\[id\\]/ipc/\\[ipcId\\]/page.tsx",
  "src/app/(app)/projects/\\[id\\]/ipc/page.tsx",
  "src/app/(app)/projects/\\[id\\]/look-ahead/page.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/inter-site-transfers-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/item-catalog-tree.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/materials-inventory-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/materials-orders-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/materials-requisitions-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/materials-transactions-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/po-print-view.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/quotation-comparison-matrix.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/requisition-detail-view.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/components/store-locations-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/dialogs/create-po-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/dialogs/create-requisition-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/dialogs/generate-po-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/dialogs/log-transaction-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/materials/stock-alerts/page.tsx",
  "src/app/(app)/projects/\\[id\\]/page.tsx",
  "src/app/(app)/projects/\\[id\\]/payments/components/aging-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/payments/components/bulk-import-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/payments/components/retention-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/payments/page.tsx",
  "src/app/(app)/projects/\\[id\\]/planning/revision/\\[versionId\\]/page.tsx",
  "src/app/(app)/projects/\\[id\\]/production/components/ProductionDashboardTab.tsx",
  "src/app/(app)/projects/\\[id\\]/subcontractors/billing/components/material-reconciliation-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/subcontractors/billing/components/reconciliation-matrix-tab.tsx",
  "src/app/(app)/projects/\\[id\\]/subcontractors/billing/dialogs/verify-bill-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/subcontractors/billing/page.tsx",
  "src/app/(app)/projects/\\[id\\]/subcontractors/page.tsx",
  "src/app/(app)/projects/\\[id\\]/tax-summary/components/helpers.ts",
  "src/app/(app)/projects/\\[id\\]/tax-summary/dialogs/log-vat-bill-dialog.tsx",
  "src/app/(app)/projects/\\[id\\]/variations/\\[voId\\]/page.tsx",
  "src/app/(app)/projects/\\[id\\]/vendors/components/vendor-detail-view.tsx",
  "src/app/(app)/projects/\\[id\\]/vendors/performance/page.tsx",
  "src/app/(app)/projects/\\[id\\]/workflow/program/page.tsx",
  "src/app/(app)/projects/\\[id\\]/workflow/rfi/components/rfi-card.tsx",
  "src/components/boq/excel-paste-dialog.tsx",
  "src/components/costs/cost-rates-card.tsx",
  "src/components/costs/cost-summary-card.tsx",
  "src/components/dashboard/progress-scurve.tsx",
  "src/components/equipment/rentals-tab.tsx",
  "src/components/equipment/vendors-tab.tsx",
  "src/components/inventory/weighbridge-calculator.tsx",
  "src/components/material-name-input.tsx",
  "src/components/materials/log-direct-material-dialog.tsx",
  "src/components/rate-catalog/copy-from-dialog.tsx",
  "src/components/ui/calendar.tsx",
  "src/components/ui/chart.tsx",
  "src/components/ui/construction-table.tsx",
  "src/components/ui/motion.tsx",
  "src/components/workflow/edit-rfi-dialog.tsx",
  "src/components/workflow/view-rfi-dialog.tsx",
  "src/lib/currency.ts",
  "src/lib/delegation.ts",
  "src/lib/report-tokens.ts",
  "src/server/routers/gantt-analytics.ts",
  "src/server/routers/jv-partner.ts",
  "src/server/routers/project-ops.ts",
  "src/server/routers/subcontractor-bill.ts",
  "src/server/routers/vendor-bill.ts",
  "src/server/utils/email.ts",
];
