/**
 * tRPC router for Approved Documents — the signed hardcopy archive.
 *
 * Any exportable entity (daily_report, rfi, ipc, boq, schedule) can have
 * multiple approved documents attached. Each document is one of:
 *   - "generated_pdf"   : a PDF generated by the PDF Designer (auto-archived)
 *   - "signed_hardcopy" : a scanned PDF of the client-signed physical copy
 *   - "supporting_doc"  : any other supporting document (email, photo, etc.)
 *
 * The DocumentTrail UI shows these as a timeline, giving a full audit trail
 * from generation → submission → client signature → archival.
 */
import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { router, protectedProcedure } from "@/server/trpc";
import { db } from "@/lib/db";
import { assertProjectMember, assertCanWrite } from "@/lib/authz";
import { audit } from "@/lib/audit";

const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10 MB — base64 encoded

const UploadSchema = z.object({
  projectId: z.string(),
  entityType: z.string(),
  entityId: z.string(),
  documentType: z.enum(["generated_pdf", "signed_hardcopy", "supporting_doc"]),
  fileName: z.string().min(1).max(300),
  fileType: z.string(),
  fileSize: z.number().positive().max(MAX_FILE_SIZE),
  data: z.string(), // base64-encoded
  signedBy: z.string().optional(),
  signedAt: z.string().datetime().optional(),
  receivedAt: z.string().datetime().optional(),
  notes: z.string().optional(),
  pdfConfig: z.string().optional(),
});

export const approvedDocumentRouter = router({
  /** List all approved documents for an entity, ordered by upload time (newest first). */
  list: protectedProcedure
    .input(z.object({
      projectId: z.string(),
      entityType: z.string(),
      entityId: z.string(),
    }))
    .query(async ({ ctx, input }) => {
      await assertProjectMember(ctx.user, input.projectId);

      const documents = await db.approvedDocument.findMany({
        where: {
          projectId: input.projectId,
          entityType: input.entityType,
          entityId: input.entityId,
        },
        orderBy: { uploadedAt: "desc" },
        include: {
          uploadedBy: { select: { id: true, name: true, role: true } },
        },
         take: 1000, // bounded (pagination sweep) — see src/lib/pagination.ts
       });

      return { documents };
    }),

  /** Get a single document (includes base64 data for download/preview). */
  get: protectedProcedure
    .input(z.object({ id: z.string(), projectId: z.string() }))
    .query(async ({ ctx, input }) => {
      await assertProjectMember(ctx.user, input.projectId);

      const doc = await db.approvedDocument.findFirst({
        where: { id: input.id, projectId: input.projectId },
        include: { uploadedBy: { select: { id: true, name: true } } },
      });
      if (!doc) throw new TRPCError({ code: "NOT_FOUND", message: "Document not found." });

      return { document: doc };
    }),

  /** Upload a new approved document (signed hardcopy, generated PDF, or supporting doc). */
  upload: protectedProcedure
    .input(UploadSchema)
    .mutation(async ({ ctx, input }) => {
      await assertCanWrite(ctx.user, input.projectId);

      // Validate base64 data size (base64 is ~33% larger than binary)
      const estimatedBytes = Math.ceil((input.data.length * 3) / 4);
      if (estimatedBytes > MAX_FILE_SIZE) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: `File too large. Max ${MAX_FILE_SIZE / 1024 / 1024}MB, got ~${Math.round(estimatedBytes / 1024 / 1024)}MB.`,
        });
      }

      const doc = await db.approvedDocument.create({
        data: {
          projectId: input.projectId,
          entityType: input.entityType,
          entityId: input.entityId,
          documentType: input.documentType,
          fileName: input.fileName,
          fileType: input.fileType,
          fileSize: input.fileSize,
          data: input.data,
          uploadedById: ctx.user.id,
          signedBy: input.signedBy || null,
          signedAt: input.signedAt ? new Date(input.signedAt) : null,
          receivedAt: input.receivedAt ? new Date(input.receivedAt) : null,
          notes: input.notes || null,
          pdfConfig: input.pdfConfig || null,
        },
      });

      await audit({
        userId: ctx.user.id,
        projectId: input.projectId,
        action: `approved_doc.upload.${input.documentType}`,
        entityType: input.entityType,
        entityId: input.entityId,
        metadata: {
          docId: doc.id,
          fileName: doc.fileName,
          documentType: doc.documentType,
          signedBy: doc.signedBy,
        },
      });

      return { document: doc };
    }),

  /** Update metadata (signedBy, signedAt, notes) without re-uploading the file. */
  update: protectedProcedure
    .input(z.object({
      id: z.string(),
      projectId: z.string(),
      signedBy: z.string().nullable().optional(),
      signedAt: z.string().datetime().nullable().optional(),
      receivedAt: z.string().datetime().nullable().optional(),
      notes: z.string().nullable().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      await assertCanWrite(ctx.user, input.projectId);

      const existing = await db.approvedDocument.findFirst({
        where: { id: input.id, projectId: input.projectId },
      });
      if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Document not found." });

      const updated = await db.approvedDocument.update({
        where: { id: input.id },
        data: {
          ...(input.signedBy !== undefined && { signedBy: input.signedBy }),
          ...(input.signedAt !== undefined && { signedAt: input.signedAt ? new Date(input.signedAt) : null }),
          ...(input.receivedAt !== undefined && { receivedAt: input.receivedAt ? new Date(input.receivedAt) : null }),
          ...(input.notes !== undefined && { notes: input.notes }),
        },
      });

      return { document: updated };
    }),

  /** Delete a document. */
  delete: protectedProcedure
    .input(z.object({ id: z.string(), projectId: z.string() }))
    .mutation(async ({ ctx, input }) => {
      await assertCanWrite(ctx.user, input.projectId);

      const existing = await db.approvedDocument.findFirst({
        where: { id: input.id, projectId: input.projectId },
      });
      if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Document not found." });

      await db.approvedDocument.delete({ where: { id: input.id } });

      await audit({
        userId: ctx.user.id,
        projectId: input.projectId,
        action: `approved_doc.delete`,
        entityType: existing.entityType,
        entityId: existing.entityId,
        metadata: { docId: existing.id, fileName: existing.fileName },
      });

      return { ok: true };
    }),
});
