import { ImageResponse } from "next/og";

export const size = {
  width: 32,
  height: 32,
};
export const contentType = "image/png";

/**
 * Dynamic app icon — a construction hard hat on a navy rounded square.
 *
 * The path matches the static PNG icons in /public/icons/ which are
 * generated by scripts/generate_helmet_icons.py. The static PNGs declared
 * in app/layout.tsx → metadata.icons take precedence for browsers; this
 * dynamic /icon route is a fallback for crawlers / link-preview bots.
 *
 * The hard hat silhouette is a single closed SVG path:
 *   • Wide brim at the bottom (extends beyond the dome on both sides)
 *   • Rounded dome on top
 *   • Small raised center ridge (real hard hats have this)
 * Bold enough to stay readable down to 32×32.
 */
const HARDHAT_PATH =
  "M 1 20 L 1 17 Q 1 16 2 16 L 5 16 L 5 12 A 7 7 0 0 1 12 5 L 10 5 " +
  "Q 10 4 11 4 L 13 4 Q 14 4 14 5 L 12 5 A 7 7 0 0 1 19 12 L 19 16 " +
  "L 22 16 Q 23 16 23 17 L 23 20 Q 23 20 22 20 L 2 20 Q 1 20 1 20 Z";

const RIDGE_PATH =
  "M 10.5 5 Q 10.5 4 11.5 4 L 12.5 4 Q 13.5 4 13.5 5 " +
  "L 13.5 11 Q 13.5 11.5 12.5 11.5 L 11.5 11.5 Q 10.5 11.5 10.5 11 Z";

export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "#0f172a",
          borderRadius: "22%",
        }}
      >
        <svg
          width="26"
          height="26"
          viewBox="0 0 24 24"
          style={{ display: "block" }}
        >
          {/* Drop shadow under brim */}
          <path
            d={HARDHAT_PATH}
            fill="#b45309"
            opacity="0.55"
            transform="translate(0,1.2)"
          />
          {/* Main helmet body */}
          <path d={HARDHAT_PATH} fill="#f59e0b" />
          {/* Highlight ridge along the top of the dome */}
          <path d={RIDGE_PATH} fill="#fbbf24" opacity="0.95" />
          {/* Tiny top highlight cap */}
          <ellipse cx="12" cy="6.2" rx="2" ry="0.7" fill="#ffffff" opacity="0.45" />
        </svg>
      </div>
    ),
    {
      ...size,
    }
  );
}
