"use client";

import { useState, useRef } from "react";
import { trpc } from "@/lib/trpc-client";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Upload, Loader2, FileText, X } from "lucide-react";
import { format } from "date-fns";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { getLocalDateString } from "@/lib/nepali-calendar";

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  projectId: string;
  entityType: string;
  entityId: string;
  /** Optional: lock the document type (e.g. always "signed_hardcopy") */
  fixedDocumentType?: "generated_pdf" | "signed_hardcopy" | "supporting_doc";
  /** Optional: pre-fill the "signed by" field with the client name */
  defaultSignedBy?: string;
};

const DOCUMENT_TYPES = [
  { value: "signed_hardcopy" as const, label: "Signed Hardcopy", desc: "Scanned PDF of the client-signed physical copy" },
  { value: "generated_pdf" as const, label: "Generated PDF", desc: "A PDF generated by the PDF Designer (auto-archive)" },
  { value: "supporting_doc" as const, label: "Supporting Document", desc: "Email, photo, or any other supporting file" },
];

const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

export function UploadSignedCopyDialog({
  open,
  onOpenChange,
  projectId,
  entityType,
  entityId,
  fixedDocumentType,
  defaultSignedBy,
}: Props) {
  const utils = trpc.useUtils();
  const [documentType, setDocumentType] = useState<"generated_pdf" | "signed_hardcopy" | "supporting_doc">(
    fixedDocumentType ?? "signed_hardcopy"
  );
  const [file, setFile] = useState<File | null>(null);
  const [signedBy, setSignedBy] = useState(defaultSignedBy ?? "");
  const [signedAt, setSignedAt] = useState("");
  const [receivedAt, setReceivedAt] = useState("");
  const [notes, setNotes] = useState("");
  const [uploading, setUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const uploadMut = trpc.approvedDocument.upload.useMutation({
    onSuccess: () => {
      utils.approvedDocument.list.invalidate({ projectId, entityType, entityId });
      toast.success("Document uploaded");
      // Reset
      setFile(null);
      setSignedBy(defaultSignedBy ?? "");
      setSignedAt("");
      setReceivedAt("");
      setNotes("");
      onOpenChange(false);
    },
    onError: (e) => toast.error(e.message),
  });

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0];
    if (!f) return;
    if (f.size > MAX_FILE_SIZE) {
      toast.error(`File too large. Max ${MAX_FILE_SIZE / 1024 / 1024}MB.`);
      return;
    }
    setFile(f);
    // Auto-set signedAt to today if it's a signed hardcopy and field is empty
    if (documentType === "signed_hardcopy" && !signedAt) {
      setSignedAt(getLocalDateString());
    }
  };

  const handleSubmit = async () => {
    if (!file) {
      toast.error("Please select a file");
      return;
    }
    setUploading(true);
    try {
      // Read file as base64
      const reader = new FileReader();
      const base64Promise = new Promise<string>((resolve, reject) => {
        reader.onloadend = () => {
          const result = reader.result as string;
          // Strip the "data:...;base64," prefix
          const base64 = result.split(",")[1] ?? result;
          resolve(base64);
        };
        reader.onerror = () => reject(new Error("Failed to read file"));
      });
      reader.readAsDataURL(file);
      const base64Data = await base64Promise;

      uploadMut.mutate({
        projectId,
        entityType,
        entityId,
        documentType,
        fileName: file.name,
        fileType: file.type || "application/octet-stream",
        fileSize: file.size,
        data: base64Data,
        signedBy: documentType === "signed_hardcopy" ? (signedBy || undefined) : undefined,
        signedAt: documentType === "signed_hardcopy" && signedAt ? new Date(signedAt).toISOString() : undefined,
        receivedAt: documentType === "signed_hardcopy" && receivedAt ? new Date(receivedAt).toISOString() : undefined,
        notes: notes || undefined,
      });
    } catch (e: any) {
      toast.error(e.message ?? "Upload failed");
    } finally {
      setUploading(false);
    }
  };

  const handleClose = () => {
    if (uploading) return;
    setFile(null);
    setSignedBy(defaultSignedBy ?? "");
    setSignedAt("");
    setReceivedAt("");
    setNotes("");
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Upload className="h-4 w-4" /> Upload Document
          </DialogTitle>
          <DialogDescription>
            Upload a signed hardcopy, generated PDF, or supporting document.
            Files are stored as base64 in the database (max 10MB).
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-3 py-2">
          {/* Document type */}
          {!fixedDocumentType && (
            <div className="space-y-1.5">
              <Label className="text-xs">Document Type</Label>
              <div className="grid grid-cols-1 gap-1">
                {DOCUMENT_TYPES.map(t => (
                  <button
                    key={t.value}
                    type="button"
                    onClick={() => setDocumentType(t.value)}
                    className={cn(
                      "rounded-md border p-2 text-left text-xs transition-colors",
                      documentType === t.value
                        ? "border-primary bg-primary/5 ring-1 ring-primary"
                        : "border-border hover:bg-muted/30"
                    )}
                  >
                    <div className="font-medium">{t.label}</div>
                    <div className="text-[10px] text-muted-foreground">{t.desc}</div>
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* File picker */}
          <div className="space-y-1.5">
            <Label className="text-xs">File</Label>
            {!file ? (
              <label className="flex items-center justify-center gap-2 rounded-md border border-dashed h-20 cursor-pointer hover:bg-muted/30 text-xs text-muted-foreground">
                <Upload className="h-4 w-4" />
                <span>Click to select a file (PDF, JPG, PNG — max 10MB)</span>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"
                  onChange={handleFileSelect}
                  className="hidden"
                />
              </label>
            ) : (
              <div className="flex items-center gap-2 rounded-md border p-2">
                <FileText className="h-4 w-4 text-primary shrink-0" />
                <div className="flex-1 min-w-0">
                  <div className="text-xs font-medium truncate">{file.name}</div>
                  <div className="text-[10px] text-muted-foreground">
                    {(file.size / 1024).toFixed(1)} KB · {file.type || "unknown"}
                  </div>
                </div>
                <button
                  onClick={() => setFile(null)}
                  className="h-6 w-6 rounded border hover:bg-muted flex items-center justify-center shrink-0"
                >
                  <X className="h-3 w-3" />
                </button>
              </div>
            )}
          </div>

          {/* Signed-by fields — only for signed hardcopies */}
          {documentType === "signed_hardcopy" && (
            <>
              <div className="space-y-1.5">
                <Label className="text-xs">Signed By (client name)</Label>
                <Input
                  value={signedBy}
                  onChange={(e) => setSignedBy(e.target.value)}
                  placeholder="e.g. Mr. Ram Sharma (Client PM)"
                  className="h-8 text-sm"
                />
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1.5">
                  <Label className="text-xs">Signed Date</Label>
                  <Input
                    type="date"
                    value={signedAt}
                    onChange={(e) => setSignedAt(e.target.value)}
                    className="h-8 text-sm"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">Received Date</Label>
                  <Input
                    type="date"
                    value={receivedAt}
                    onChange={(e) => setReceivedAt(e.target.value)}
                    className="h-8 text-sm"
                  />
                </div>
              </div>
            </>
          )}

          {/* Notes */}
          <div className="space-y-1.5">
            <Label className="text-xs">Notes (optional)</Label>
            <Textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={2}
              placeholder="e.g. Received via courier, courier slip #12345"
              className="text-sm"
            />
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={handleClose} disabled={uploading}>Cancel</Button>
          <Button onClick={handleSubmit} disabled={uploading || !file}>
            {uploading ? <Loader2 className="h-3 w-3 mr-1 animate-spin" /> : <Upload className="h-3 w-3 mr-1" />}
            Upload
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
